project:
  type: book
  output-dir: docs

book:
  title: "ICJ Setting Up"
  author: "Christian McDonald"
  date: "7/18/2023"
  chapters:
    - href: index.qmd
      text: Home
    - setup-part-1.md
    - setup-part-2.md
  appendices:
    - codespaces.md
    - gcloud.md
    - vscode-goodies.md
    - old_windows_setup.md

format:
  html:
    theme: cosmo
    toc: true
    code-overflow: wrap
