project:
  type: book
  output-dir: docs

book:
  title: "ICJ Setting Up"
  author: "Christian McDonald"
  date: last-modified
  chapters:
    - href: index.qmd
      text: Home
    - setup-part-1.qmd
    - setup-part-2.qmd
  appendices:
    - vscode-goodies.qmd
    - setup-local-dev.qmd
    - setup-gcloud-cli.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-overflow: wrap
    link-external-icon: true
    link-external-newwindow: true
